### ISSUE TITLE
Errata suggestion: question 1.16 wrong expression letter used

### ISSUE THREAD

**Issue by antoinebertram** [jaccokrijnen/modelling-computing-systems-errata#5]
When the expression of q is expressed more succinctly they use p again instead of q.

> The following proposition q expresses that each name is written on a piece of paper held by exactly one other boy:
> q = ( JonF V JonO) /\ ( ,JonF V ,JonO)
> /\ ( FonJ V FonO) /\ ( ,FonJ V ,FonO)
> /\ (OonJ V OonF) /\ ( ,OonJ V ,OonF).
> Again this could be expressed more succinctly:
> p = (JonF XOR JonO) /\ (FonJ XOR FonO) /\ (OonJ XOR OonF).

**Comment by wouter-swierstra** [comment]
@antoinebertram - definitely! This is a great example where XOR is more useful than OR. I wouldn't classify it as a 'mistake' in the book - but you do raise a fair point.

**Comment by antoinebertram** [comment]
I only meant to point out that the letter used is p and I think it should be q (see the last line of the quoted text).

**Comment by wouter-swierstra** [comment]
Ah - now I understand. I'll add this to the errata!
